name: Add Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/github-script@7.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const issue = context.payload.issue;
            const projectNumber = 1;
            const columnName = 'TODO';

          
            const columns = await github.projects.listColumns({
              project_id: projectNumber
            });

            let columnId = null;

        
            columns.data.forEach((column) => {
              if (column.name === columnName) {
                columnId = column.id;
              }
            });

   
            if (!columnId) {
              const newColumn = await github.projects.createColumn({
                project_id: projectNumber,
                name: columnName
              });
              columnId = newColumn.data.id;
            }


            await github.projects.createCard({
              column_id: columnId,
              content_id: issue.id,
              content_type: 'Issue'
            });
