name: add-issue
on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project
        run: |

          ISSUE_NUMBER=$(jq --raw-output .issue.number $GITHUB_EVENT_PATH)
          REPO_NAME=$(jq --raw-output .repository.name $GITHUB_EVENT_PATH)
          

          curl -X POST -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/projects/1/columns/47fc9ee4/cards" \
            -d "{\"content_id\": $ISSUE_NUMBER, \"content_type\": \"Issue\"}"

